services:
  database:
    image: mongo:latest
    container_name: yoga_db
    networks:
      - backend
    volumes:
      - mongodata:/data/db

  frontend:
    build:
      context: ./frontend
    container_name: yoga_frontend
    ports:
      - $FRONTENDPORT:5173
    networks:
      - frontend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: yoga_server
    ports:
      - $BACKENDPORT:3000
    networks:
      - backend
      - frontend
    environment:
      - MONGODB_URI=$MONGODB
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/frontend/dist
    depends_on:
      - database

networks:
  backend:
  frontend:

volumes:
  mongodata:
